libs =
#import libs += libhello%lib{hello}

exe{glslang-tools}: {hxx cxx}{**} $libs StandAlone/testscript

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
